modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
issueTrackerURL="https://github.com/starforcraft/Imgur-Display/issues/new/choose"
[[mods]]
modId="imgurdisplay"
version="${file.jarVersion}"
displayName="Imgur Display"
displayURL="https://www.curseforge.com/minecraft/mc-mods/imgur-display"
logoFile="logo.png"
credits="Thanks for downloading this mod."
authors="Ultramega"
description="Display images from imgur."

[[dependencies.imgurdisplay]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.imgurdisplay]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,)"
    ordering="NONE"
    side="BOTH"
